In [1]:
#Day 13

import numpy as np
v1 = np.array([1, 2, 3])
print(v1)




[1 2 3]


In [ ]:
# Mathatical foundations In AI 

# Linear Algebra - It is the study of vectors, matrices, and linear transformations.
#                  It provides the mathematical framework for representing and manipulating data in high-dimensional spaces.

# Probability - It is the study of uncertainty and randomness.
#               It helps in modeling and understanding the likelihood of events and outcomes.

# Statitics - It is the science of collecting, analyzing, interpreting, presenting, and organizing data.
#             It provides tools for making inferences and drawing conclusions from data.

# Hypothesis Testing - It is a statistical method used to test assumptions or claims about a population based on sample data.
#                      It helps in determining whether there is enough evidence to support or reject a hypothesis.

In [ ]:
#methods in numpy

#np.zeros(shape) - Creates an array filled with zeros.
#np.ones(shape) - Creates an array filled with ones.
#np.linspace (start, stop, num) - Creates an array of evenly spaced numbers over a specified interval.
#np.eye(n) - Creates an identity matrix of size n x n.
#np.arrange(start, stop, step) - Creates an array with a range of values.

In [401]:
import numpy as np

scalar = 5
print(scalar)  # Scalar - a single number

vector = np.array([1, 2, 3]) #np.array - it is a function in numpy that creates an array
print(vector.ndim)  # Vector - a one-dimensional array

matrix = np.array([[1, 2], [3, 4]])  # Creating a 2x2 matrix 
print(matrix.ndim) #ndim - it is property fo get the dimention

print(np.zeros((3, 3)))  # Creating a 3x3 matrix filled with zeros

print(np.ones((2, 2)))  # Creating a 2x2 matrix filled with ones

5
1
2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [400]:
n = np.linspace(0, 10, 5)  # Creating an array of 5 evenly spaced numbers between 0 and 10
print(n)

[ 0.   2.5  5.   7.5 10. ]


In [6]:
n = np.eye(3)  # Creating a 3x3 identity matrix
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1 + v2)  # Element-wise addition of two vectors

print(v1 - v2)  # Element-wise subtraction of two vectors

print(v1 * v2)  # Element-wise multiplication of two vectors

print(v1 / v2)  # Element-wise division of two vectors

print(np.dot(v1, v2))  # Dot product of two vectors 
1
print(np.cross(v1, v2))  # Cross product of two vectors

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32
[-3  6 -3]


In [14]:
v1 = np.array([[1, 2, 3]])
print(v1.T) # Transpose of a vector (converts row vector to column vector)

[[1]
 [2]
 [3]]


In [3]:
# Inverse Of a Matrix
import numpy as np
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(matrix)
print(np.linalg.inv(matrix))  # Inverse of a matrix using numpy's linear algebra module

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [8]:
# Determinant of a Matrix
import numpy as np
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(np.linalg.det(matrix))  # Determinant of a matrix using numpy's linear algebra module

print("----------------------------------------------------------------------------------------------------------------------------------------")

from numpy.linalg import det, inv
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(det(matrix))  # Determinant of a matrix using numpy's linear algebra module

print("----------------------------------------------------------------------------------------------------------------------------------------")

print(inv(matrix))  # Inverse of a matrix using numpy's linear algebra module 

-306.0
----------------------------------------------------------------------------------------------------------------------------------------
-306.0
----------------------------------------------------------------------------------------------------------------------------------------
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [11]:
#eigenvalues and eigenvectors
from numpy.linalg import eig
matrix = np.array([[4, 2], [1, 3]])

eigenvalues, eigenvectors = eig(matrix)  # Calculate eigenvalues and eigenvectors  
print("Eigenvalues:", eigenvalues)  # Print eigenvalues
print("Eigenvectors:", eigenvectors)  # Print eigenvectors

# Eigenvalues - They are scalars that indicate how much a transformation stretches or compresses a vector.
# Eigenvectors - They are vectors that remain in the same direction after a transformation, only scaled by the corresponding eigenvalue.

Eigenvalues: [5. 2.]
Eigenvectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [12]:
# Principal Component Analysis (PCA)
# Dimentionality reduction technique that transforms data into a lower-dimensional space while preserving variance.
# It identifies the directions (principal components) that maximize variance in the data.
# It is commonly used for feature extraction and visualization in high-dimensional datasets.

In [ ]:
a = np.random.rand(2, 30)  # np.random.rand generates a random matrix with values between 0 and 1
print("Random Matrix:\n", a)  # Print the random matrix

Random Matrix:
 [[0.3598266  0.3072394  0.27907368 0.5107523  0.70669868 0.06119596
  0.354954   0.84358396 0.38705488 0.20424842 0.87058019 0.65817996
  0.56250785 0.35280381 0.13510226 0.84148901 0.72589243 0.3331495
  0.3052861  0.65262547 0.2531336  0.45434696 0.81623091 0.65920679
  0.30805148 0.51685369 0.27292107 0.24040789 0.15952569 0.70162586]
 [0.60092732 0.05591609 0.55760543 0.73156201 0.82111325 0.28708443
  0.2192942  0.01197954 0.74930724 0.71159556 0.47393023 0.22089155
  0.71802116 0.5279328  0.21850439 0.53628116 0.62055521 0.75160661
  0.04397838 0.38876974 0.10695219 0.60713929 0.9861333  0.31211781
  0.14376126 0.99548562 0.11505604 0.40990109 0.81485176 0.456966  ]]
